# Generated by Django 4.2.17 on 2025-01-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_companyuser_id_alter_companyuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
