# Generated by Django 4.2.17 on 2025-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_companyuser_brand_name_alter_companyuser_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
