# Generated by Django 4.2.17 on 2025-01-09 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='base.cartitem'),
        ),
    ]
