# Generated by Django 4.2.17 on 2025-01-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_cart_cart_total_alter_cartitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
