# Generated by Django 4.2.17 on 2025-01-09 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='brand_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='gstin',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
